name: emote_utils
description: Emote utilities for text-based games.
version: 2.1.0
homepage: https://github.com/chrisnorman7/emote_utils

environment:
  sdk: ">=2.13.0 <3.0.0"

dev_dependencies:
  pedantic:
  test:
