name: emote_utils
description: Emote utilities for text-based games.
version: 2.0.1
homepage: https://github.com/chrisnorman7/emote_utils

environment:
  sdk: '>=2.8.4 <3.0.0'

#dependencies:
#  path:

dev_dependencies:
  pedantic:
  test:
