name: emote_utils
description: Emote utilities for text-based games.
version: 1.0.2
homepage: https://github.com/chrisnorman7/emote_utils

environment:
  sdk: '>=2.8.1 <3.0.0'

#dependencies:
#  path:

dev_dependencies:
  pedantic:
  test:
